tweaks

diff --git a/cluster-deploy b/cluster-deploy
--- a/cluster-deploy
+++ b/cluster-deploy
@@ -57,6 +57,13 @@ function esxi_deploy () {
     TARGET_REMOTE_USER_PASSWORD_HASH=`sudo python3 -c "${PYTHON_CMD}"`
   fi 
 
+  echo -e " ${TC} Verifying host availability${NC}"
+  ansible all -i $INVENTORY_FILE -m ping -u $REMOTE_USER
+  if [ $? -ne 0 ]; then
+    echo "FAIL: ${CLUSTER_TYPE_NAME} host access verification failed!"
+    exit 1
+  fi
+
   ansible-playbook -i $INVENTORY_FILE ansible/esxi-create-vms-start.yml --extra-vars "ova_template=${OVA_TEMPLATE_FILE} cluster_pkg_folder=${CLUSTER_PKG_FOLDER}"
   if [ $? -ne 0 ]; then
    echo "There is a problem with the ESXi init-pre script"
@@ -92,8 +99,12 @@ function esxi_deploy () {
   rm $TEMP_SCRIPT_PATH/esxi-set-statics
   
   ansible all -i $INVENTORY_FILE -m ping -u $REMOTE_USER
+  if [ $? -ne 0 ]; then
+    echo "FAIL: ${CLUSTER_TYPE_NAME} host access verification failed!"
+    exit 1
+  fi
+  
   echo
-
   echo -e "Building cluster: ${CLUSTER_TYPE_NAME}"
   ansible-playbook -i $INVENTORY_FILE ansible/$CLUSTER_TYPE.yml  --extra-vars="cluster_pkg_folder=${CLUSTER_PKG_FOLDER}"
   if [ $? -ne 0 ]; then
diff --git a/cluster-update b/cluster-update
--- a/cluster-update
+++ b/cluster-update
@@ -7,11 +7,15 @@ ANSIBLE_DISPLAY_SKIPPED_HOSTS=false
 function k8s_patch () {
   
   echo 
-  echo -e " ${TC}Verifying host access:${NC}"
+  echo -e " ${TC}Verifying host availability:${NC}"
   echo
   ansible all -i $INVENTORY_FILE -m ping -u $REMOTE_USER
-  echo
+  if [ $? -ne 0 ]; then
+    echo "FAIL: ${CLUSTER_TYPE_NAME} host access verification failed!"
+    exit 1
+  fi
 
+  echo
   echo -e " ${TC}Updating cluster: ${CLUSTER_TYPE_NAME}${NC}"
   echo
   ansible-playbook -i $INVENTORY_FILE ansible/k8s-update.yml  --extra-vars="cluster_pkg_folder=${CLUSTER_PKG_FOLDER}"
