moved source of rhel7-setup script to clusters folder

diff --git a/node-packer/build b/node-packer/build
--- a/node-packer/build
+++ b/node-packer/build
@@ -22,9 +22,16 @@ if [ "`uname -r | grep Microsoft | wc -l | xargs`" == "1" ]; then
   echo "Building in Windows Mode using cmd.exe..."
   PACKER_CMD="/mnt/c/Windows/System32/cmd.exe /k \"packer build cluster-node-${IMAGE}.json && exit\""
 fi
+
 if [ "$2" != "" ]; then
-  RHEL_LIC=$2
-  PACKER_CMD="packer build -var rhel_lic=${RHEL_LIC} cluster-node-${IMAGE}.json"
+  if [ "$3" == "" ]; then
+    echo
+    echo "Error: No license key found. Make sure rhel.lic is located in the clusters folder."
+    exit 1
+  fi
+  RHEL_LIC=$3 
+  RHEL_FOLDER=$2
+  PACKER_CMD="packer build -var rhel_folder=${RHEL_FOLDER} -var rhel_lic=${RHEL_LIC} cluster-node-${IMAGE}.json"
 fi
 
 if [ "$IMAGE" == "centos7" ] || [ "$IMAGE" == "photon" ] || [ "$IMAGE" == "atomic7" ]  || [ "$IMAGE" == "rhel7" ]; then
