add canal, metallb, longhorn, dashboard, nginx to rocky9

diff --git a/node-packer/build b/node-packer/build
--- a/node-packer/build
+++ b/node-packer/build
@@ -19,6 +19,10 @@ PACKER_CMD="packer build rockylinux9.pkr.hcl"
 
 echo 'Building VM image:' 
 eval $PACKER_CMD
+if [ $? -ne 0 ]; then
+  echo "FAILED! There was a problem with the build."
+  exit 1
+fi
 
 mv ./cluster-node/*.ova ./output_ovas
 rm -rf ./cluster-node
